/*
 * This source file was generated by the Gradle 'init' task
 */
package testprojectjava;

import org.junit.jupiter.api.Test;

import easybank.Main;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        Main classUnderTest = new Main();
        // assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
